### PR TITLE
Initial attempt to incorporate HMcode

### PR DESCRIPTION
**Pull request by alexander-mead**
Hi Antony,

I've finally got around to trying to incorporate HMcode within CAMB in the same way that HALOFIT is currently incorporated. I've got a local version of this working and I think it would be useful to have this merged with the master CAMB version at some point.

To achieve this I have added the HMcode source code into halofit_ppf.f90, and I also had to create two new 'types' within modules.f90, which HMcode then uses. I've created this pull request so that these changes may be reviewed and hopefully merged. I've tested the changes on my local CAMB copy for a few example cosmologies and the results seem to be accurate (as in, the non-linear spectrum agrees well with my own personal version of HMcode). I think you mentioned that you had a test suite you could run to check that any changes weren't interfering with other parts of the code?

HMcode can be used for the non-linear spectrum by setting halofit_version=5 in the params.ini file. I have it working for standard cosmologies, w(a)=w_0+(1-a)w_a dark energy models and massive neutrinos.

Cheers,
Alexander

### CODE REVIEW

**Comment by cmbant** [comment]
Great, thanks! As you can see above the Travis auto-test seems to have hung on one of the non-flat models, any idea why that might be? I think you can run the tests locally by running

      python python/CAMB_test_files.py testfiles --make_ini

(as in the full test script tests/tun_tests.sh which runs on Travis).

Other comments:

Could the "cosmology" and "tables" types be put as private types in halofit.f90 instead, since not used elsewhere, leaving modules unchanges? 

I would rename "meadfit" to "halofit_mead" to be consistent with the other options (and make halofit_mead public).

For error reports, generally if you stop should use "error stop" rather than "stop" (to give the right return code). But if an error may just indicate the input model is out of range, rather than stopping it would probably be better to set global_error_flag as the other halofit versions (so, for example, CosmoMC can just reject the model rather than stopping in its tracks).

Is there any reason you can't use the ns value from CAMB rather than fixing it to one?

Also I would advise against changing the default settings in the .ini file to avoid unexpected changes when people pull updates.

Thanks!

**Comment by alexander-mead** [comment]
Hi again,

Okay, if I run the tests locally I get some strange error messages:

Fails in : ['params_counts_opts_T_T_T_T.ini', 'params_counts_opts_T_T_T_F.ini', 'params_counts_opts_T_T_F_T.ini', 'params_counts_opts_T_T_F_F.ini', 'params_counts_opts_T_F_T_T.ini', 'params_counts_opts_T_F_T_F.ini', 'params_counts_opts_T_F_F_T.ini', 'params_counts_opts_T_F_F_F.ini', 'params_counts_opts_F_T_T_T.ini', 'params_counts_opts_F_T_T_F.ini', 'params_counts_opts_F_T_F_T.ini', 'params_counts_opts_F_T_F_F.ini', 'params_counts_opts_F_F_T_T.ini', 'params_counts_opts_F_F_T_F.ini', 'params_counts_opts_F_F_F_T.ini', 'params_counts_opts_F_F_F_F.ini', 'params_counts_1bin.ini', 'params_counts_lmax1.ini', 'params_counts_lmax2.ini', 'params_counts_overlap.ini', 'params_lensing_base.ini', 'params_21cm_base.ini', 'params_21cm_base2.ini', 'params_counts_lens.ini']

and I also see quite a few of:

Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG

but I get these messages even when halofit_ppf.f90 is not modified, so I'm not sure what's going on. I'm using gfortran 5.2 on OS X.

Anyway, otherwise I don't see anything obviously wrong with the tests, and they seem to complete using Travis on Github too now. I assume the tests are using HMcode somehow and I'm not just testing standard CAMB with no non-linear additions? The problem with the curved model seems to have gone away, but I'm not sure why. 

Regarding your other comments:

Could the "cosmology" and "tables" types be put as private types in halofit.f90 instead, since not used elsewhere, leaving modules unchanges?

Done.

I would rename "meadfit" to "halofit_mead" to be consistent with the other options (and make halofit_mead public).

Done.

For error reports, generally if you stop should use "error stop" rather than "stop" (to give the right return code). But if an error may just indicate the input model is out of range, rather than stopping it would probably be better to set global_error_flag as the other halofit versions (so, for example, CosmoMC can just reject the model rather than stopping in its tracks).

Most of the STOP commands indicate that subroutines have been called with incorrect options and so I have changed these to ERROR STOP. For these to trigger someone would have to modify the HMcode source and they would have to have done something seriously wrong.

The other STOP commands *might* be activated for particularly strange cosmological models if the integration to calculate sigma(R) fails for some reason. I've not come across any models like this when running over large numbers of cosmological models recently (but it was a problem I had in the past), so I have also changed these to ERROR STOP too. Let me know if you think they would be better set to trigger the global_error_flag and how best to do this

Is there any reason you can't use the ns value from CAMB rather than fixing it to one?

It seems that ns is on a different standing to the other cosmological parameters in CAMB. I guess this is because the same transfer functions can be used to make the spectra for any number of ns values. I can get values for ns from CP%InitPower%an(1), but I have just set the index to be '1' and don't really know how I would find the index of the value of n_s that is currently being computed. Any suggestions? This is a problem that the standard halofit never encounters because nothing in it depends exclusively on n_s.

A related question that I have is: is CAMB_PK%num_z ever anything other than 1? The halofit module has a loop over CAMB_PK%num_z but it never seems to be anything other than 1. This is even if I run a parameters file with transfer_num_redshifts>1 , in which case it still seems halofit is just called separately for each redshift.

Also I would advise against changing the default settings in the .ini file to avoid unexpected changes when people pull updates.

Sure, I've reversed the changes and simply added a line with the new options on it. halofit_version=5 corresponds to HMcode and halofit_version=6 corresponds to a pure version of the halo model with none of the tweaks I introduced to improve accuracy. I thought that this may be of interest to some people.

Cheers,
Alexander

**Comment by cmbant** [comment]
Thanks for all the changes!

Sorry, the counts file errors are not a problem - I should have said to run the test program locally using the "--no_sources" option. Perhaps Travis just hung/timed out the first time, certainly seems OK now.

However if the settings now default to not using HMcode, the tests will not be using it. You'd need to add another "params.append" to python/CAMB_test_files.py to test the halofit_mead option, which would be a good idea. I'd have to add the expected output files to the test outputs repository for the comparison check to work though; if you send me the correct outputs I can push to https://github.com/cmbant/CAMB_test_outputs/ (or you could make a pull request there).

CAMB will error in the non-linear code if P%InitPower%nn>1, so you can assume it is one. 

But if you set do_nonlinear=3 (including non-linear CMB lensing), I think num_z will be >1, so do need to support that.

Antony

**Comment by alexander-mead** [comment]
Hi Antony,

I guess my tests were running without testing HMcode directly then - so not
great tests! Anyway, I changed this and ran the tests with the default
non-linear model set to HMcode. The problem with the Om_k=0.04 model
re-appeared but I have now fixed that (I had made some assumptions about
the shape of the power spectrum at very large scales that were
inappropriate for curved models). I changed the halofit_default to
halofit_mead, purely to check the tests complete with the Github version of
the tests.

You'd need to add another "params.append" to python/CAMB_test_files.py to
test the halofit_mead option, which would be a good idea.

I added this line, but I guess this means it will just perform a couple of
tests for HMcode but without varying the cosmology or anything like that?
Is this fine? If so I will send you the correct output files for the
comparisons.

But if you set do_nonlinear=3 (including non-linear CMB lensing), I think
num_z will be >1, so do need to support that.

Okay, I've now added proper support for num_z>1.

Let me know what further steps are necessary.

Cheers,
Alex

**Comment by cmbant** [comment]
Thanks, sounds good. I guess you didn't commit the change to the test files? You can add as many test variations as you think are helpful (without slowing down too much).

If you can email me the correct outputs I can upload them for comparison.

Antony

**Comment by alexander-mead** [comment]
Hi Antony,

I just uploaded a version of halofit_ppf.f90 that I'm quite happy with. The
Travis tests look like they completed okay apart from the checks agains the
testfiles you don't have - the files I generate from running the tests are
attached.

I didn't add any variations apart from a basic test of HMcode
(halofit_version=5) and the vanilla halo model calculation
(halofit_version=6).

Cheers,
Alex

**Comment by cmbant** [comment]
Thanks for the contribution!

**Pull request merged**
