### PR TITLE
ENH patches for gfortran 4.8; no -ffast-math w/ python

### PR DESCRIPTION
**Pull request by beckermr**
Hi @cmbant! I have added a version of the patching I did for conda here. 

Things here:
- gfortran 4.8 compatibility
- removed the use of `-ffast-math` per the discussion [here](https://github.com/conda-forge/staged-recipes/pull/6824). (TLDR, it mucks with python's numerics after the module is imported.)

Also, I didn't add the patches in the fortran for importing the data for the camb executable. I realized that they might muck with independent installations of the code when people are using conda also, but not pulling camb from conda. These staying the feedstock repo seems fine.

### CODE REVIEW

**Comment by cmbant** [comment]
Thanks for this. Makefile_main might need a "PYFFLAGS?= $(FFLAGS)" to work with ifort (and other builds calling Makefile_main but not from the CAMB Makefile). Also not sure about the change to .gitignore?

**Comment by cmbant** [comment]
Thanks. I guess to ignore the camb binary but not the camb path in the subfolder, should keep "camb" but add "!camb/" in .gitignore.

**Comment by cmbant** [comment]
Thanks. To see pycamb but not the camb binary, probably can keep camb but add !camb/

**Comment by beckermr** [comment]
Whoops. The double comment was due to the github outage and me submitting something twice. lol. 

I added the last change the gitignore.

**Pull request merged**
