### PR TITLE
HMcode 2020

### PR DESCRIPTION
**Pull request by alexander-mead**
This pull request adds the 2020 version of HMcode to CAMB.

### CODE REVIEW

**Comment by alexander-mead** [comment]
Please do not merge this yet. I wanted to check that the Travis tests pass. Or do these no longer run?

**Comment by alexander-mead** [comment]
This now passes `python3 setup.py test`.

**Comment by cmbant** [comment]
Thanks, I see the paper is also out, great! Did you also check the python interface? I think the parameter names and options etc may be not consistent at the moment.  It would also be nice to add a unit-test specific to the new options (in python-only would be fine).

If possible I would also try to keep it backward compatible in terms of names, e.g. so if people want to reproduce Planck they can use the same-named parameter as in the published files. i.e. if you want to rename things it would be better to add more-specific synonyms for new usage but maintaining compatibility/reproducibility with the old name.

**Comment by alexander-mead** [comment]
To address the second 'backward compatibility' paragraph above, would it be sufficient to reinstate `HALOFIT_mead = 5`, but then to also keep `HALOFIT_mead2016 = 5` and have both of these as public simultaneously?

**Comment by cmbant** [comment]
I think that should be fine

**Comment by alexander-mead** [comment]
I think the main bit of Fortran coding is all finished and ready to go now. I've checked that I can run `>camb params.ini` and get results that agree with my private version of HMcode for the new 2020 non-linear model and also the baryonic feedback model. I have exposed a new parameter `logT_AGN`  that can be in the ini file and which controls the level of feedback in the new model.

The only thing now missing is a unit-specific test. Can you point me to the place in the code where these are done so that I can copy the format?

**Comment by cmbant** [comment]
Great. It's usually easiest and best to put tests via the python interface - see camb.test.camb_test.py

**Comment by alexander-mead** [comment]
I have now added tests for all `HMcode` versions. They are the same  as the existing test for the `mead` version, in that they check only one cosmology, and at only k, a pair. I would be happy for this to be merged now.

**Comment by alexander-mead** [comment]
Although please note: I've been checking the `HMcode` versions that coded up in `CAMB` against my own development version. I was checking over large numbers of random cosmologies, and the agreement was usually pretty good, <0.1% in the residual, but I was getting some models with worse agreement (>1%). I found a number of small differences between the two versions that account for most of these differences, and after fixing these I now get <1% agreement all of the time. In order to improve the match I had to upgrade the accuracy parameter on the sigma(R) integration in the `CAMB` version, so it might run more slowly now. Could you check this and let me know if it would be a problem? I have changed it from `3e-4` to `1e-4`, but it could always be reverted if the speed was a problem.

As far as I can tell, the one thing that is now preventing me from improving on the <1% agreement is the difference between the techniques for interpolating the linear power spectrum: my development version uses cubic interpolation whereas you changed this to linear, but with more points, in `CAMB`. This gives some differences around BAO scales after I damp the BAO wiggles. 

Personally, I think that <1% agreement is fine, given the 2.5% quoted HMcode2020 accuracy, but I leave this here in order to be completely open.

**Comment by cmbant** [comment]
With enough points, a series of  linear and bicubic based on the same original P(k) sampling should be able to give the same accuracy? What fractional slowdown did you find from the accurate change? (though I agree probably good enough for most purposes)

**Comment by alexander-mead** [comment]
Sorry for the long radio silence on this. I just double checked the timings. For 16 z and kmax=200 I find that the timing of the HMcode part of the calculation increases from ~1.15e-2 to ~1.20e-2 (a ~5% increase) seconds when tightening the accuracy parameter from 3e-4 to 1e-4. There is not a significant difference if massive neutrinos are in the calculation or not. The runtimes of the 2016 and 2020 versions of HMcode are more or less identical. For the 2020 HMcode with the AGN feedback model the runtime ~doubles to ~2.7e-2 seconds, because the halo model calculation needs to run 3 times in this case.

I think that this represents a small fraction of the overall calculation time in all cases, and the ~5% increase in runtime incurred from tightening that accuracy parameter seems acceptable to me.

**Comment by cmbant** [comment]
Sounds reasonable, is this then ready for merge?

**Comment by alexander-mead** [comment]
Almost... I just want to check a couple of things (to do with comparing my personal HMcode to the CAMB version) early next week. I'll get back to you then.

**Comment by alexander-mead** [comment]
This is now ready to go!

**Comment by cmbant** [comment]
Great thanks. Could you suggest a short summary change text for the squash merge commit description?

**Comment by alexander-mead** [comment]
I guess 'Added support for HMcode2020' would do?

**Comment by cmbant** [comment]
Certainly concise! linking to your paper, does that describe all relevant changes?

**Comment by alexander-mead** [comment]
I think so! All the details of the new model are in the paper. I have retained support for the 2015 and 2016 versions (via `halofit_version = 8` and `5`, as before) while adding support for the 2020 versions (`halofit_version = 9` and `10` for without/with feedback respectively). There is a new parameter, `HMcode_logT_AGN = 7.8`, which governs the way feedback affects the power when `halofit_version = 10`, but everything is described in the paper.

I have not changed any of the default settings, and the non-linear model still defaults to Takahashi... although this maybe could/should be updated...

**Pull request merged**
