### PR TITLE
HM_code updates

### PR DESCRIPTION
**Pull request by cmbant**
From https://github.com/cmbant/CAMB/pull/48, with some small speed ups and tidies.

### CODE REVIEW

**Comment by alexander-mead** [comment]
Okay, wow, that was fast. I checked this and it looks fine to me, and it also passes all of my private tests so I would be very happy for this to be merged.

I did some timing tests and this ensures that HMcode now runs x3 faster than it did before #48 and your changes have made it run x2 faster than after my changes in #48. Do you know which of your changes represents the biggest time saving? The only extra residual I see in my tests is a tiny oscillation, <0.1% of the power, at slightly smaller scales than the first BAO wiggle (k=0.3 or so).

Out of curiosity, I noticed that some of the `PARAMETERS` now have a `._dl` trailing (e.g., `REAL(dl), PARAMETER :: zinf_Dolag=10._dl` in line 119, whereas in the main body of the code you removed many of my decimals (e.g. `(4.*pi/3.)` -> `(4*pi/3)` in line 1392). What is the reason for this? Probably something I don't understand about Fortran types. I also noticed that you left some `PARAMETERS` in the body of the code with the trailing decimal `.`, but to some you added the `._dl`. Again, any reason for this.

**Comment by cmbant** [comment]
Thanks for checking. The innermost loop of sigma(r) was the "find" routine to look up P(k). So I think the biggest speedup was avoiding the binary search (using the regular log spacing) and then linear rather than cubic interpolation (this last change is the only thing that actually changes the result, with most impact around the baryon oscillations).

Is the 1% difference from your commits to before at  high redshift OK? Seems quite large given good agreement at low redshift.

In Fortran 1 is integer, 1. is real and 1._dl (with dl as in camb) is double precision. Double * integer always gives double as expected, but 1. can give e.g. 1.000004206348  after converting to double. So using either integers (where safe) or doubles gives a more numerically reproducible result. (though exactly what happens with 1. may be compiler and optimisation dependent). I may have missed some; it's not really important.

**Comment by alexander-mead** [comment]
Thanks for the information. Very useful.

Regarding the z=10 thing: I changed both the way the sigma(R) integral is done (no longer split into two regimes depending on R; integral for low R was previously done using a combination of two parts, one of which was approximate) and how the linear power spectrum is extrapolated to small scales (previously it was extrapolated using a P(k) \propto ln(k)^2 k^(ns-4), now it is a power law). If taken literally (which I probably wouldn't encourage) the halo model would say that the non-linear power at high z would depend haloes whose formation depends on very high-k power, which would govern the mass function of very tiny haloes.

However, it's a little bit difficult for me to worry about the non-linear power at z=10 too much... all of my numerical requirements were governed by wanting to have numerical convergence for k<10 and z<2, although I think I am now confident the numerical precision is much greater than this.

**Comment by cmbant** [comment]
It looks as though the high redshift difference is as one approaches kmax. Although the difference is small, the entire nonlinear correction is small, so the fractional change in HMcode looks quite large.  But since it seems to behave sensibly away from kmax, should be OK.

At high redshift there is some kind of ground truth from next order SPT (and beyond), do you know if it matches reasonably on to that?

**Comment by alexander-mead** [comment]
In general there is no guarantee that HMcode (or the standard halo model) will match neatly onto any analytical perturbation theory result. The standard halo model can be thought of as linear theory + one-halo term, which clearly doesn't 'know' anything about perturbation theory. HMcode is slightly cleverer, and has parameters that allow it to match-ish known perturbation theory results at low-k for vanilla LCDM. The most obvious example of this is the ~2% dip in power, compared to linear, at z=0 between 0.01<k<0.1, which some people call 'pre-virialisation', and which is in HMcode. However, the way this is implemented is not very sophisticated as it relies on some of the HMcode tuned parameters in both the two- and one-halo terms. I wouldn't guarantee that it would work over a very general cosmological parameter space, or at higher z. Trying to make a new halo model that transitioned smoothly from linear to PT to halo power would make a good project for someone though...

**Pull request merged**
