### PR TITLE
CAMB baseline test, benchmark and profiler

### PR DESCRIPTION
**Pull request by mraveri**
Dear Antony,

I would like to contribute to CAMB development but before doing any change to the code I made a simple test suite to make sure that I was not destroying something in the process.

It's pretty rudimentary and relies on bash scripts that limit the portability of the code but I think it's quite effective and might be useful.

Cheers,
Marco

### CODE REVIEW

**Comment by cmbant** [comment]
Thanks, though a fairly comprehensive Travis auto-test has been added recently to the vehre_formatted branch (which is a modernised merge of CAMB and CAMB sources). This could be backported to master by just cutting out anything to do with CAMB soruces. How does your compare with that?

**Comment by mraveri** [comment]
They seem quite similar in spirit with some differences:
1) Mine is thought to be used locally while developing, i.e. modify something and test immediately before doing other modifications and committing/pushing. For this reason, to avoid machine dependencies, the baseline results are produced on the machine where the test is run. I think this adds flexibility because one can add/remove a parameter file to the test routine at any stage. Integration with Travis can still be added with a bit of scripting.
2) Does not use Python to compare the results but numdiff because it was easier to code in this way. Can be extended to work with Python as the test in vehre_formatted but requires Python stuff that is on that branch.
3) Contains also benchmark and profiling that might be useful when targeting performances. A possible extension might be to add automatic omp scalability analysis.

**Comment by cmbant** [comment]
Great, thanks. The python tests can of course also be run locally, the Travis stuff is just to automate it. Seems as though we are basically doing the same thing: script to produce a load of fiducial results, and script to compare with new results with previous results. The benchmarking and profiling stuff sounds like a neat addition. Do you think they could easily be merged? Would be nice to have just one test suite rather than two, and there are certainly many ways in which the python tests could be improved.

**Comment by mraveri** [comment]
Perfect! I'll have a deeper look at the python test these days to see what is needed to merge them!

**Comment by cmbant** [comment]
I've just updated the python tests so they are now also on master (and use the new much simpler Docker service using the CosmoBox image)

**Comment by cmbant** [comment]
I'm going to close this for now, since would presumably require changes to incorporate into the current Travis tests.

**Comment by mraveri** [comment]
Ops, I forgot this open PR!
Thanks for closing it and sorry!

Will try to resume working on these things as soon as I have some time!

**Pull request closed without merging**
