### PR TITLE
Fixed bug with 'z' not being defined when Tcb_Tcbnu_ratio is called, also speed ups

### PR DESCRIPTION
**Pull request by alexander-mead**
I fixed the bug where 'z' is undefined when Tcb_Tcbnu_ratio is called in 'fill_plintab' subroutine. I moved the assignment of 'z' to before the loop where Tcb_Tcbnu_ratio is called. 

Separately I have also sped up the integration routines by using a better integration method, similar to the 'qsimp' routine in Numerical Recipes. The end result of this is that run-time when non-linear CMB lensing is being done by HMcode is only 10% slower than when using HALOFIT; before it was more like 30% slower.

### CODE REVIEW

**Comment by cmbant** [comment]
Thanks, sounds good, though looks as though you've based this off a slightly old version of master hence the conflicts? (I also push the z issue fix earlier today while fixing some things for pypi install).

**Comment by alexander-mead** [comment]
Ah, right, I guess I had a slightly older version on my computer. I think
the main difference was the change to the HM_verbose logical from the ihm
integer. I resolved the conflicts as I saw them but it has now just failed
the Travis tests. Looking at the report from those it does not look like
halofit_ppf.f90 is the problem...

**Comment by cmbant** [comment]
I think the test failure is because the changes are changing the results of HM code: the test fails on 

        camb.set_halofit_version('mead')
        _, _, pk = results.get_nonlinear_matter_power_spectrum(params=pars, var1='delta_cdm', var2='delta_cdm')
        self.assertAlmostEqual(pk[0][160], 824.6, delta=0.5)

**Comment by alexander-mead** [comment]
Ah, okay, what is the tolerance for 'almost equal'? In my own test (note
singular, and fairly limited in scope) I saw changes in the matter power of
 ~0.1% around k=1. In the lensing the changes were less than this for
l<2000 (which is the maximum I looked at).

I guess I would not consider these changes problematic given the ~5%
accuracy of the matter-power model provided by HMcode. However, maybe they
get worse for some specific cosmological models?

**Comment by cmbant** [comment]
Fixing the z bug did not actually change anything enough to fail the test. So it seems like it must be due to the other changes - was there anything substantive there, or should it just be a speed up? (if the latter any change is presumably a bug)

**Comment by alexander-mead** [comment]
Okay, yes, updating the integration routines made larger differences to
P(k) compared to fixing the z bug. I guess I would not describe this small
difference in the output power spectra as a bug though - the integration
routines have an accuracy parameter that I have set to be 1e-3 by default,
and changing the integration routines has produced changes in the power
that are of the order of this accuracy parameter, which is not surprising
to me given that I changing the integration method.

Given the accuracy of the HMcode as a power spectrum estimation method
(~5%) it didn't seem worthwhile to set the integration accuracy to anything
more stringent than this, although I think the integration could be done to
machine precision if desired.

**Comment by cmbant** [comment]
If you are confident it is correct within errors, you can just update the value in the test to reflect the new value. I would agree that if the error on the non-linear correction is only 1e-3 that sounds fine.
(the speed up should certainly be useful!)

**Comment by alexander-mead** [comment]
Hi Antony,

Please don't merge this yet. I was just checking that I could get the tests to pass. I just need to check a couple of other things.

Cheers,
Alex

**Comment by alexander-mead** [comment]
Okay. This is all fine now. As you suggested, I checked that the old and new integration routines converged when the accuracy parameters of both were increased. However, it turned out that the difference between the old and new integration schemes was responsible for only a small part of the test failure. 

A larger problem was that I had also set the number of entries in a look-up table ('n' in halomod_init) to half of the previous value, which was changing the overall result for the non-linear spectrum by more substantial amount (~ 0.1%). This provided only a small speed up and so I reverted the value and the tests past. If speed was very important in the future then this number could always be decreased again at the expense of some accuracy (~ 0.1%), which is tiny compared to the overall ~5% accuracy of the method.

**Comment by cmbant** [comment]
Sounds good, thanks!

**Comment by cmbant** [comment]
I think this is a problem: sum_new in growint can be accessed before it is defined. e.g. with ifort runtime checking on

forrtl: severe (194): Run-Time Check Failure. The variable 'nonlinear_mp_sigint0_$SUM_NEW' is being used in 'halofit_ppf.f90(1735,17)' without being defined
f

**Pull request merged**
