### PR TITLE
HMcode numerical accuracy

### PR DESCRIPTION
**Pull request by alexander-mead**
After some conversations with @tilmantroester I found some numerical inaccuracies in HMcode in CAMB that create occasional problems for some cosmological models at the few per cent level. These inaccuracies are mainly due to lack of convergence in some integration routines. They would manifest in the HMcode P(k) not being smooth as cosmological parameters are varied.

The pull request is an attempt to fix some of the numerical inaccuracy. It is not complete, so please don't merge it if it does pass the tests! I just wanted to start the pull request to see if it did pass the Travis tests and to check that it could be easily integrated.

Again, I stress that these problems are occasional, and occur for particular cosmological parameter combinations, and only affect the power at the few per cent level. The quoted accuracy of HMcode compared to numerical power spectra is 5%, so I don't see this as a major cause for concern. I do think it matters to fix this though, because it may matter for things like Fisher forecasting, and also there is no reason to have numerical integrals not properly converge.

I checked that these changes do not have a significant impact on any comparison of the accuracy of HMcode compared to numerical simulations (those plots still look good to 5%).

### CODE REVIEW

**Comment by cmbant** [comment]
Thanks, will this make it slower?
Perhaps consider also changing everything to double precision to avoid all the dble casting?

**Comment by alexander-mead** [comment]
Increasing the accuracy parameters would make things slower... but also I changed some look-up tables to being stored as log, and this increases the speed more than it is slowed down, so HMcode is now faster. Previously these look-up tables were being converted to log every time they were being used, which was extremely inefficient.

I will look into the double precision thing. Would that just be a case of converting all `REAL ::` to `REAL(dl) ::`?

**Comment by cmbant** [comment]
Great. And yes (+removing now-redundant dble casts)

**Comment by alexander-mead** [comment]
Okay, assuming this latest commit passes the tests then I think this is ready to merge. The main changes this pull request has are to improve the accuracy of numerical integrations within HMcode. Inaccuracy in some numerical integrals was causing occasional few-% 'step' changes in P(k) as cosmological parameters were varied at some specific k. Most notably for higher z (z>1.5) at smaller scales (k>1). I also did quite a lot of code refactoring to help me debug. Note that these inaccuracies are occasional, and almost always had an effect lower than the quoted 5% accuracy of HMcode. I think the biggest discrepancy I came across was 7%, but that was for some strange combination cosmological parameters (usually the combination of low n_s, low h and low sigma_8 is the worst).

In addition, two bugs were found and removed:

- The linear growth function was being calculated incorrectly for massive-neutrino cosmologies. Because of the way the code works this did not affect the large-scale power accuracy (which is always taken from CAMB) but did affect calculations of halo concentrations, which had a few-% level impact on P(k) at smaller scales (k>1) for higher neutrino masses (m_nu > 0.3 eV).

- The effective spectral index at the collapse scale was being calculated via a numerical derivative of the sigma(R) function, a function that itself was being calculated by a moderate-accuracy integration. Taking the numerical derivative occasionally encountered spikes in the numerical integral which led to quite wrong values of the effective spectral index. I have changed this so that it is now computed via numerical integration, which is far more stable.

As a result of this the CAMB-HMcode combination now runs slightly more slowly (some of the increase in numerical accuracy of integrals being offset by storing look-up tables in log). In some tests I was running I got around a 6% increase in run time with the enhanced accuracy. If this is unacceptable then I can try decreasing the accuracy again to increase run time. Let me know.

**Comment by alexander-mead** [comment]
That was 6% of the total run time, so HMcode would be worse than that. I can do some proper benchmarking next week and get back to you on that.

**Comment by cmbant** [comment]
OK thanks.
ifort says your f interface should have a result type (I think you can delete real(d), external:: f if you have the interface). There are also a bunch of unused arguments which maybe could be eliminated (e.g. z and k in fdamp and fv, plus several others).

**Comment by alexander-mead** [comment]
I did some benchmarking. HMcode itself, with the improved accuracy, seems to run around 33% slower for non-neutrino LCDM cosmologies, however, it now seems to be around 10% faster for massive neutrino cosmologies. Does this sound okay? I can do some more rigorous benchmarking if necessary. Are there any standardised timing tests you use?

**Comment by cmbant** [comment]
Thanks, I don't have specific timing tests. Do you know which inner subroutines/loops dominate the time?
(It may also be possible to improve the OPENMP parallelization - I think I did that first time, but by limited by the structure of the code without significant refactoring)

**Comment by cmbant** [comment]
Btw, can you answer https://github.com/cmbant/CAMB/issues/44?

**Comment by alexander-mead** [comment]
Regarding the timing. I did some more involved benchmarking and find that it is mainly the calculation of sigma(R) (standard deviation in the linear density field as a function of scale R) that dominates the calculation time. The loop that computes the look-up table for this already has OMP parallelisation, which I think you put in.

For the timing, what are your requirements? Would you just prefer it not to be any slower than before? I can look at degrading some of the accuracy parameters and see if my own tests continue to pass after the degradation. At the moment I am not sure what I am aiming for.

**Comment by cmbant** [comment]
There are no specific requirements, but ideally the execution time should be a small fraction of the total.
My guess is some changes to how you do the integrals could make large time savings.

If the time is mostly in sigma(r), it looks as though you are integrating sigma_integrand which calls grow and find_pk via p_lin. The former (grow) can be pre-computed for each z rather than being called each time inside sigma_integrand. The latter currently seems to do Lagrange interpolation. Have you tried simply precomputing the with fine fixed sampling, then doing direct linear or cubic interpolation removing many of these nested function calls? Finding the exact indices using fixed spacing can save time compared to generic n or log n search, as can using simple interpolation. [btw, I never really liked this back-integration of P(k), since CAMB actually has P(k,z), but that's another issue..] 
find_pk also seems to be doing one pre-computable log.

If you do need to call Lagrange_polynomial with n =2, would be better to just make specific hard-coded n=2 function rather than calling generic loops.

You could also consider replacing integrate() with a direct summation over more optimally-sampled points. CAMB almost never uses generic integration routines, because typically they waste time calculating parts of the integrand with high accuracy that make little difference to the final results.

**Comment by alexander-mead** [comment]
Okay, these are all great suggestions. Unfortunately I have run out of time that I can work on this at the moment. My time working at UBC comes to and end this week and then I will start in Barcelona in November. I will be more-or-less offline for the 3 months in between. It would be my preference that this branch be merged with the master before I go offline (assuming the Travis tests pass).

In this latest commits I have degraded the accuracy parameter on the sigma(R) integration to 3e-4 (before this pull request it was 1e-3, and prior to these last commits it was 1e-4). This degradation ensures that the run time is faster than it was before this pull request (by around 25%) and it still passes all of my own tests (still accurate compared to my private version of the code and still certainly reproducing the FrankenEmu P(k) at the 5% level for k<10 and z<2). It is also much more numerically stable than the version in the master branch. 

After I move to Barcelona I can look at improving the run time if this is necessary. I have left myself some TODO messages in the code based on your suggestions for where things can be sped up.

**Comment by cmbant** [comment]
OK thanks - it does look quite a bit faster now. I see around a 1% difference compared to master for PK(k=2,z=0). Is that expected? [the unit tests all pass because almost all of them use Takahashi for non-linear]

**Comment by cmbant** [comment]
PS. the 1% was actually z=10 not z=0.

**Comment by cmbant** [comment]
Actually, since you have rebin_pk=True, looks like you can already do some of the suggestions, e.g. trivially changing to ifind_pk_interpolation=1, I also made a few other simple changes and switched to linear interpolation for pk (now you have many more points, seems to be accurate to <2e-4 - do you think this is OK?. See
https://github.com/cmbant/CAMB/pull/49

**Pull request closed without merging**
